name = "hasanhub"
main = "workers/app.ts"
compatibility_date = "2025-02-02"

[[d1_databases]]
binding = "DB"
database_name = "hasanhub"
database_id = "3cb465bd-8698-4c06-941c-0154e1fd72e7"

[triggers]
crons = [
  "*/15 * * * *",
  "0 * * * *",
  "0 3 * * *",
  "0 4 * * *"
]

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1
