import { createRequestHandler } from "react-router";
import { cronScheduleMap, runCronJob, type CronJob } from "../app/cron/jobs";

type VersionMetadata = {
  id?: string;
  tag?: string;
  timestamp?: string;
};

export type Env = {
  DB: D1Database;
  DB_QUERY_CACHE: KVNamespace;
  YOUTUBE_API_KEY?: string;
  TWITCH_CLIENT_ID?: string;
  TWITCH_CLIENT_SECRET?: string;
  TOP_OF_THE_HOUR_SECRET?: string;
  CF_VERSION_METADATA?: VersionMetadata;
};

const CACHE_NAMESPACE = "hasanhub:ssr";
const CACHE_VERSION_PARAM = "__cv";
const CACHE_DEBUG_PARAM = "cacheDebug";

const getMode = () => {
  // Guard against `import.meta.env` being undefined in Workers.
  if (typeof import.meta !== "undefined") {
    const env = (import.meta as { env?: { MODE?: string } }).env;
    if (env?.MODE) return env.MODE;
  }
  return "production";
};

const importServerBuild = async () => {
  const viteMeta = (import.meta as {
    env?: {
      MODE?: string;
      DEV?: boolean;
    };
  })?.env;

  const isDevBuild =
    viteMeta?.MODE === "development" || viteMeta?.DEV === true;

  if (isDevBuild) {
    try {
      return await import("virtual:react-router/server-build");
    } catch (error) {
      console.warn(
        "Dev server build import failed, falling back to compiled build",
        { error: String(error) }
      );
    }
  }

  try {
    return await import("../build/worker/index.js");
  } catch (error) {
    try {
      return await import("../build/server/index.js");
    } catch (fallbackError) {
      console.error("Failed to load React Router build artifacts", {
        primaryError: String(error),
        fallbackError: String(fallbackError),
      });
      throw fallbackError;
    }
  }
};

const handleRequest = createRequestHandler(
  // The server build is generated by `react-router build` before deploy.
  // @ts-ignore - build output does not exist in source tree during compile.
  () => importServerBuild(),
  getMode()
);

const parseCacheControlInt = (value: string, directive: string) => {
  const match = new RegExp(`${directive}\\s*=\\s*(\\d+)`, "i").exec(value);
  return match ? Number.parseInt(match[1] ?? "", 10) : null;
};

const isCacheable = (cacheControl: string | null) => {
  if (!cacheControl) return false;
  const value = cacheControl.toLowerCase();
  if (
    value.includes("no-store") ||
    value.includes("no-cache") ||
    value.includes("private")
  ) {
    return false;
  }

  const sMaxAge = parseCacheControlInt(value, "s-maxage");
  const maxAge = parseCacheControlInt(value, "max-age");
  const ttl = sMaxAge ?? maxAge;
  return typeof ttl === "number" && ttl > 0;
};

const getCacheDebugFlag = (request: Request) => {
  if (request.headers.get("X-Cache-Debug") === "1") return true;
  const url = new URL(request.url);
  return url.searchParams.get(CACHE_DEBUG_PARAM) === "1";
};

const resolveCronJob = (cron: string): CronJob | null => {
  const entry = Object.entries(cronScheduleMap).find(
    ([, schedule]) => schedule === cron
  );
  return entry ? (entry[0] as CronJob) : null;
};

const hasVaryWildcard = (vary: string | null) =>
  Boolean(vary && vary.split(",").some((token) => token.trim() === "*"));

const getCacheVersion = (env: Env) =>
  env.CF_VERSION_METADATA?.id ?? "unversioned";

const toHandlerRequest = (request: Request) =>
  new Request(request.url, request);

const createCacheKey = (request: Request, env: Env) => {
  const keyUrl = new URL(request.url);
  keyUrl.searchParams.delete(CACHE_DEBUG_PARAM);
  keyUrl.searchParams.set(CACHE_VERSION_PARAM, getCacheVersion(env));
  return new Request(keyUrl.toString(), { method: "GET" });
};

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext) {
    const handlerRequest = toHandlerRequest(request);

    if (handlerRequest.method !== "GET") {
      return handleRequest(handlerRequest, {
        cloudflare: { env, ctx },
      });
    }

    const requestCacheControl = handlerRequest.headers.get("Cache-Control") ?? "";
    const requestCacheControlValue = requestCacheControl.toLowerCase();
    const bypassRead =
      requestCacheControlValue.includes("no-cache") ||
      requestCacheControlValue.includes("max-age=0") ||
      handlerRequest.headers.has("Pragma");
    const skipWrite = requestCacheControlValue.includes("no-store");
    const hasSensitiveHeaders = handlerRequest.headers.has("Authorization");
    const cacheDebug = getCacheDebugFlag(handlerRequest);

    const cache = await caches.open(CACHE_NAMESPACE);
    const cacheKey = createCacheKey(handlerRequest, env);

    if (!bypassRead && !hasSensitiveHeaders) {
      try {
        const cached = await cache.match(cacheKey);
        if (cached) {
          if (cacheDebug) {
            console.log("cache:hit", {
              url: handlerRequest.url,
              cacheControl: cached.headers.get("Cache-Control"),
              cacheVersion: getCacheVersion(env),
            });
            const response = new Response(cached.body, cached);
            response.headers.set("X-Cache-Debug", "hit");
            response.headers.set("X-Cache-Version", getCacheVersion(env));
            return response;
          }
          return cached;
        }
      } catch (error) {
        console.warn("cache:match-error", {
          url: handlerRequest.url,
          error: String(error),
        });
      }
    }

    if (cacheDebug) {
      console.log("cache:miss", {
        url: handlerRequest.url,
        bypassRead,
        hasSensitiveHeaders,
        requestCacheControl: requestCacheControl || null,
        cacheVersion: getCacheVersion(env),
      });
    }

    const response = await handleRequest(handlerRequest, {
      cloudflare: { env, ctx },
    });

    if (cacheDebug) {
      console.log("cache:response", {
        url: handlerRequest.url,
        status: response.status,
        cacheControl: response.headers.get("Cache-Control"),
        cdnCacheControl:
          response.headers.get("CDN-Cache-Control") ??
          response.headers.get("Cloudflare-CDN-Cache-Control"),
        setCookie: response.headers.has("Set-Cookie"),
      });
    }

    if (
      response.status === 200 &&
      !skipWrite &&
      !hasSensitiveHeaders &&
      !response.headers.has("Set-Cookie") &&
      !hasVaryWildcard(response.headers.get("Vary"))
    ) {
      const edgeCacheControl =
        response.headers.get("CDN-Cache-Control") ??
        response.headers.get("Cloudflare-CDN-Cache-Control") ??
        response.headers.get("Cache-Control");

      if (isCacheable(edgeCacheControl)) {
        try {
          const cacheSource = response.clone();
          const toCache = new Response(cacheSource.body, cacheSource);
          if (edgeCacheControl) {
            toCache.headers.set("Cache-Control", edgeCacheControl);
          }
          ctx.waitUntil(cache.put(cacheKey, toCache));
          if (cacheDebug) {
            console.log("cache:stored", {
              url: handlerRequest.url,
              cacheControl: edgeCacheControl,
              cacheVersion: getCacheVersion(env),
            });
          }
        } catch (error) {
          console.warn("cache:put-error", {
            url: handlerRequest.url,
            error: String(error),
          });
        }
      } else if (cacheDebug) {
        console.log("cache:skip", {
          url: handlerRequest.url,
          reason: "not-cacheable",
          cacheControl: edgeCacheControl,
        });
      }
    } else if (cacheDebug) {
      console.log("cache:skip", {
        url: handlerRequest.url,
        reason: "response-or-request-not-cacheable",
        status: response.status,
        skipWrite,
        hasSensitiveHeaders,
        hasSetCookie: response.headers.has("Set-Cookie"),
      });
    }

    if (cacheDebug) {
      const debugResponse = new Response(response.body, response);
      debugResponse.headers.set("X-Cache-Debug", "miss");
      debugResponse.headers.set("X-Cache-Version", getCacheVersion(env));
      return debugResponse;
    }

    return response;
  },
  async scheduled(
    controller: ScheduledController,
    env: Env,
    ctx: ExecutionContext
  ) {
    const cron = controller.cron ?? "";
    const job = resolveCronJob(cron);

    if (!job) {
      console.warn("cron:unmapped", { cron });
      return;
    }

    const startedAt = new Date().toISOString();
    console.log("cron:start", { cron, job, startedAt });

    ctx.waitUntil(
      (async () => {
        try {
          const result = await runCronJob(job);
          console.log("cron:success", {
            cron,
            job,
            startedAt,
            finishedAt: new Date().toISOString(),
            result,
          });
        } catch (error) {
          console.error("cron:error", { cron, job, error });
          throw error;
        }
      })()
    );
  },
} satisfies ExportedHandler<Env>;
