import { createRequestHandler } from "react-router";
import { cronScheduleMap, runCronJob, type CronJob } from "../app/cron/jobs";

type VersionMetadata = {
  id?: string;
  tag?: string;
  timestamp?: string;
};

export type Env = {
  DB: D1Database;
  DB_QUERY_CACHE: KVNamespace;
  YOUTUBE_API_KEY?: string;
  TWITCH_CLIENT_ID?: string;
  TWITCH_CLIENT_SECRET?: string;
  TOP_OF_THE_HOUR_SECRET?: string;
  CF_VERSION_METADATA?: VersionMetadata;
};

const getMode = () => {
  // Guard against `import.meta.env` being undefined in Workers.
  if (typeof import.meta !== "undefined") {
    const env = (import.meta as { env?: { MODE?: string } }).env;
    if (env?.MODE) return env.MODE;
  }
  return "production";
};

const importServerBuild = async () => {
  const viteMeta = (import.meta as {
    env?: {
      MODE?: string;
      DEV?: boolean;
    };
  })?.env;

  const isDevBuild =
    viteMeta?.MODE === "development" || viteMeta?.DEV === true;

  if (isDevBuild) {
    try {
      return await import("virtual:react-router/server-build");
    } catch (error) {
      console.warn(
        "Dev server build import failed, falling back to compiled build",
        { error: String(error) }
      );
    }
  }

  try {
    return await import("../build/worker/index.js");
  } catch (error) {
    try {
      return await import("../build/server/index.js");
    } catch (fallbackError) {
      console.error("Failed to load React Router build artifacts", {
        primaryError: String(error),
        fallbackError: String(fallbackError),
      });
      throw fallbackError;
    }
  }
};

const handleRequest = createRequestHandler(
  // The server build is generated by `react-router build` before deploy.
  // @ts-ignore - build output does not exist in source tree during compile.
  () => importServerBuild(),
  getMode()
);

const resolveCronJob = (cron: string): CronJob | null => {
  const entry = Object.entries(cronScheduleMap).find(
    ([, schedule]) => schedule === cron
  );
  return entry ? (entry[0] as CronJob) : null;
};

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext) {
    return handleRequest(request, {
      cloudflare: { env, ctx },
    });
  },
  async scheduled(
    controller: ScheduledController,
    env: Env,
    ctx: ExecutionContext
  ) {
    const cron = controller.cron ?? "";
    const job = resolveCronJob(cron);

    if (!job) {
      console.warn("cron:unmapped", { cron });
      return;
    }

    const startedAt = new Date().toISOString();
    console.log("cron:start", { cron, job, startedAt });

    ctx.waitUntil(
      (async () => {
        try {
          const result = await runCronJob(job);
          console.log("cron:success", {
            cron,
            job,
            startedAt,
            finishedAt: new Date().toISOString(),
            result,
          });
        } catch (error) {
          console.error("cron:error", { cron, job, error });
          throw error;
        }
      })()
    );
  },
} satisfies ExportedHandler<Env>;
