import type { ExportedHandler } from "@cloudflare/workers-types";
import { createRequestHandler } from "react-router";
import {
  cronScheduleMap,
  getCronOrigin,
  runCronJob,
  type CronJob,
} from "../app/cron/jobs";

export type Env = {
  DB: D1Database;
  YOUTUBE_API_KEY?: string;
  TWITCH_CLIENT_ID?: string;
  TWITCH_CLIENT_SECRET?: string;
  TOP_OF_THE_HOUR_SECRET?: string;
  CRON_ORIGIN?: string;
};

const getMode = () => {
  // Guard against `import.meta.env` being undefined in Workers.
  if (typeof import.meta !== "undefined") {
    const env = (import.meta as { env?: { MODE?: string } }).env;
    if (env?.MODE) return env.MODE;
  }
  return "production";
};

const handleRequest = createRequestHandler(
  // The server build is generated by `react-router build` before deploy.
  // @ts-ignore - build output does not exist in source tree.
  () => import("../build/server/index.js"),
  getMode()
);

const parseCacheControlInt = (value: string, directive: string) => {
  const match = new RegExp(`${directive}\\s*=\\s*(\\d+)`, "i").exec(value);
  return match ? Number.parseInt(match[1] ?? "", 10) : null;
};

const isCacheable = (cacheControl: string | null) => {
  if (!cacheControl) return false;
  const value = cacheControl.toLowerCase();
  if (
    value.includes("no-store") ||
    value.includes("no-cache") ||
    value.includes("private")
  ) {
    return false;
  }

  const sMaxAge = parseCacheControlInt(value, "s-maxage");
  const maxAge = parseCacheControlInt(value, "max-age");
  const ttl = sMaxAge ?? maxAge;
  return typeof ttl === "number" && ttl > 0;
};

const getCacheDebugFlag = (request: Request) => {
  if (request.headers.get("X-Cache-Debug") === "1") return true;
  const url = new URL(request.url);
  return url.searchParams.get("cacheDebug") === "1";
};

const resolveCronJob = (cron: string): CronJob | null => {
  const entry = Object.entries(cronScheduleMap).find(
    ([, schedule]) => schedule === cron
  );
  return entry ? (entry[0] as CronJob) : null;
};

export default {
  async fetch(request, env, ctx) {
    if (request.method !== "GET") {
      return handleRequest(request, {
        cloudflare: { env, ctx },
      });
    }

    const requestCacheControl = request.headers.get("Cache-Control") ?? "";
    const requestCacheControlValue = requestCacheControl.toLowerCase();
    const bypassRead =
      requestCacheControlValue.includes("no-cache") ||
      requestCacheControlValue.includes("max-age=0") ||
      request.headers.has("Pragma");
    const skipWrite = requestCacheControlValue.includes("no-store");
    const hasSensitiveHeaders = request.headers.has("Authorization");
    const cacheDebug = getCacheDebugFlag(request);

    const cache = caches.default;
    const cacheKey = new Request(request.url, { method: "GET" });

    if (!bypassRead && !hasSensitiveHeaders) {
      const cached = await cache.match(cacheKey);
      if (cached) {
        if (cacheDebug) {
          console.log("cache:hit", {
            url: request.url,
            cacheControl: cached.headers.get("Cache-Control"),
          });
          const response = new Response(cached.body, cached);
          response.headers.set("X-Cache-Debug", "hit");
          return response;
        }
        return cached;
      }
    }

    if (cacheDebug) {
      console.log("cache:miss", {
        url: request.url,
        bypassRead,
        hasSensitiveHeaders,
        requestCacheControl: requestCacheControl || null,
      });
    }

    const response = await handleRequest(request, {
      cloudflare: { env, ctx },
    });

    if (cacheDebug) {
      console.log("cache:response", {
        url: request.url,
        status: response.status,
        cacheControl: response.headers.get("Cache-Control"),
        cdnCacheControl:
          response.headers.get("CDN-Cache-Control") ??
          response.headers.get("Cloudflare-CDN-Cache-Control"),
        setCookie: response.headers.has("Set-Cookie"),
      });
    }

    if (
      response.status < 500 &&
      !skipWrite &&
      !hasSensitiveHeaders &&
      !response.headers.has("Set-Cookie")
    ) {
      const edgeCacheControl =
        response.headers.get("CDN-Cache-Control") ??
        response.headers.get("Cloudflare-CDN-Cache-Control") ??
        response.headers.get("Cache-Control");

      if (isCacheable(edgeCacheControl)) {
        const toCache = new Response(response.body, response);
        if (edgeCacheControl) {
          toCache.headers.set("Cache-Control", edgeCacheControl);
        }
        ctx.waitUntil(cache.put(cacheKey, toCache.clone()));
        if (cacheDebug) {
          console.log("cache:stored", {
            url: request.url,
            cacheControl: edgeCacheControl,
          });
        }
      } else if (cacheDebug) {
        console.log("cache:skip", {
          url: request.url,
          reason: "not-cacheable",
          cacheControl: edgeCacheControl,
        });
      }
    } else if (cacheDebug) {
      console.log("cache:skip", {
        url: request.url,
        reason: "response-or-request-not-cacheable",
        status: response.status,
        skipWrite,
        hasSensitiveHeaders,
        hasSetCookie: response.headers.has("Set-Cookie"),
      });
    }

    if (cacheDebug) {
      const debugResponse = new Response(response.body, response);
      debugResponse.headers.set("X-Cache-Debug", "miss");
      return debugResponse;
    }

    return response;
  },
  async scheduled(controller, env, ctx) {
    const cron = controller.cron ?? "";
    const job = resolveCronJob(cron);

    if (!job) {
      console.warn("cron:unmapped", { cron });
      return;
    }

    const origin = getCronOrigin(env);
    const startedAt = new Date().toISOString();
    console.log("cron:start", { cron, job, origin, startedAt });

    ctx.waitUntil(
      (async () => {
        try {
          await runCronJob(job, origin);
          console.log("cron:success", {
            cron,
            job,
            origin,
            startedAt,
            finishedAt: new Date().toISOString(),
          });
        } catch (error) {
          console.error("cron:error", { cron, job, origin, error });
          throw error;
        }
      })()
    );
  },
} satisfies ExportedHandler<Env>;
